Fix the sqlcmd PATH issue

diff --git a/.github/workflows/synchdb-ci.yml b/.github/workflows/synchdb-ci.yml
--- a/.github/workflows/synchdb-ci.yml
+++ b/.github/workflows/synchdb-ci.yml
@@ -29,8 +29,8 @@ jobs:
     - name: Install PostgreSQL build dependencies
       run: |
         echo "Install PostgreSQL build dependencies"
-        # sudo apt-get update
-        # sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache
+        sudo apt-get update
+        sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache
     
     - name: Clone and build PostgreSQL
       timeout-minutes: 30
@@ -39,12 +39,12 @@ jobs:
         cd postgres
         git checkout REL_16_3
         echo "Build PostgreSQL "
-        # ./configure
-        # make
-        # sudo make install
-        # cd contrib
-        # make
-        # sudo make install
+        ./configure
+        make
+        sudo make install
+        cd contrib
+        make
+        sudo make install
     
     - name: Clone SynchDB
       run: |
@@ -56,26 +56,26 @@ jobs:
     - name: Build and install Debezium Runner Engine
       run: |
         echo "build DBZ"
-        # cd postgres/contrib/synchdb
-        # make build_dbz
-        # sudo make install_dbz
+        cd postgres/contrib/synchdb
+        make build_dbz
+        sudo make install_dbz
     
     - name: Build and install SynchDB PostgreSQL Extension
       run: |
         echo "install SynchDB "
-        # cd postgres/contrib/synchdb
-        # make || exit 1
-        # sudo make install || exit 1
+        cd postgres/contrib/synchdb
+        make || exit 1
+        sudo make install || exit 1
     
     - name: Configure linker
       run: |
         echo "configure Java"
-        # JAVA_PATH=$(which java)
-        # JDK_HOME_PATH=$(readlink -f ${JAVA_PATH} | sed 's:/bin/java::')
-        # JDK_LIB_PATH=${JDK_HOME_PATH}/lib
-        # echo $JDK_LIB_PATH | sudo tee -a /etc/ld.so.conf.d/x86_64-linux-gnu.conf
-        # echo $JDK_LIB_PATH/server | sudo tee -a /etc/ld.so.conf.d/x86_64-linux-gnu.conf
-        # sudo ldconfig
+        JAVA_PATH=$(which java)
+        JDK_HOME_PATH=$(readlink -f ${JAVA_PATH} | sed 's:/bin/java::')
+        JDK_LIB_PATH=${JDK_HOME_PATH}/lib
+        echo $JDK_LIB_PATH | sudo tee -a /etc/ld.so.conf.d/x86_64-linux-gnu.conf
+        echo $JDK_LIB_PATH/server | sudo tee -a /etc/ld.so.conf.d/x86_64-linux-gnu.conf
+        sudo ldconfig
     
     - name: Set up test environment
       run: |
@@ -93,10 +93,8 @@ jobs:
         echo "Docker logs for MySQL:"
         docker logs mysql || echo "No MySQL container found"
         id=$(docker ps | grep sqlserver | awk '{print $1}')
-        echo "check docker $id opt folder"
-        docker exec -i $id ls -l /opt/ 
         echo "check docker $id sqlcmd command"
-        docker exec -i $id ls -l /opt/mssql-tools/bin/sqlcmd || { echo "sqlcmd not found on the sqlserver docker"; exit 1; }
+        docker exec -i $id ls -l /opt/mssql-tools18/bin/sqlcmd || { echo "sqlcmd not found on the sqlserver docker"; exit 1; }
         
     - name: Check Docker daemon
       run: |
@@ -126,12 +124,10 @@ jobs:
       run: |
         docker ps
         id=$(docker ps | grep sqlserver | awk '{print $1}')
-        echo "check sqlcmd command"
-        docker exec -i $id ls -l /opt/mssql-tools/bin/sqlcmd
         echo "copy inventory SQL "
         docker cp postgres/contrib/synchdb/inventory.sql $id:/
-        docker exec -i $id /opt/mssql-tools/bin/sqlcmd -U sa -P 'Password!' -i /inventory.sql
-        docker exec -i $id /opt/mssql-tools/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "SELECT COUNT(*) from orders"
+        docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -i /inventory.sql
+        docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "SELECT COUNT(*) from orders"
     - name: Check installation
       run: |
         ldd postgres/contrib/synchdb/synchdb.so
@@ -167,18 +163,18 @@ jobs:
         
         while [ $attempt -le $max_attempts ]; do
           echo "Attempt $attempt of $max_attempts"
-          syncing_src_count=$(docker exec -i $id /opt/mssql-tools/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "SELECT COUNT(*) from orders" -h -1)
+          syncing_src_count=$(docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "SELECT COUNT(*) from orders" -h -1)
           syncing_dst_count=$(psql -d test_db -t -c "SELECT COUNT(*) from inventory.orders;" | tr -d ' ')
           
           if [ "$syncing_src_count" = "$syncing_dst_count" ]; then
             echo "Initial sync complete. Adding new record to source."
-            docker exec -i $id /opt/mssql-tools/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "INSERT INTO orders(order_date, purchaser, quantity, product_id) VALUES ('2024-01-01', 1003, 2, 107)"
+            docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "INSERT INTO orders(order_date, purchaser, quantity, product_id) VALUES ('2024-01-01', 1003, 2, 107)"
             
             inner_max_attempts=10
             inner_attempt=1
             while [ $inner_attempt -le $inner_max_attempts ]; do
               echo "Attempt $inner_attempt of $inner_max_attempts for new record sync"
-              new_syncing_src_count=$(docker exec -i $id /opt/mssql-tools/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "SELECT COUNT(*) from orders" -h -1)
+              new_syncing_src_count=$(docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -d testDB -Q "SELECT COUNT(*) from orders" -h -1)
               new_syncing_dst_count=$(psql -d test_db -t -c "SELECT COUNT(*) from inventory.orders;" | tr -d ' ')
               
               if [ "$new_syncing_dst_count" = "$new_syncing_src_count" ]; then
