Update synchdb-ci.yml

diff --git a/.github/workflows/synchdb-ci.yml b/.github/workflows/synchdb-ci.yml
--- a/.github/workflows/synchdb-ci.yml
+++ b/.github/workflows/synchdb-ci.yml
@@ -110,8 +110,6 @@ jobs:
         echo "Docker logs for MySQL:"
         docker logs mysql || echo "No MySQL container found"
         id=$(docker ps | grep sqlserver | awk '{print $1}')
-        echo "check docker $id sqlcmd command"
-        docker exec -i $id ls -l /opt/mssql-tools18/bin/sqlcmd || { echo "sqlcmd not found on the sqlserver docker"; exit 1; }
         export PATH=$PATH:/usr/lib/postgresql/${{ fromJson(matrix.pg_version).major }}/bin
         mkdir -p /var/run/postgresql
         sudo chown -R $(whoami) /var/run/postgresql
@@ -125,6 +123,34 @@ jobs:
         pg_ctl -D synchdbtest start
         echo "PostgreSQL status:"
         pg_ctl -D synchdbtest status
+    - name: Prepare MySQL test database
+      run: |
+        echo "MySQL container status:"
+        docker ps | grep mysql
+        echo "Attempting to connect to MySQL..."
+        docker exec -i mysql mysql -uroot -pmysqlpwdroot -e "SELECT VERSION();" || { echo "Failed to connect to MySQL"; docker logs mysql; exit 1; }
+        docker exec -i mysql mysql -uroot -pmysqlpwdroot << EOF
+        GRANT replication client ON *.* TO mysqluser;
+        GRANT replication slave ON *.* TO mysqluser;
+        GRANT RELOAD ON *.* TO 'mysqluser'@'%';
+        FLUSH PRIVILEGES;
+        EOF
+        echo "Showing grants for mysqluser:"
+        docker exec -i mysql mysql -uroot -pmysqlpwdroot -e "SHOW GRANTS FOR mysqluser;"
+    - name: Prepare SQL Server test database
+      run: |
+        docker ps
+        id=$(docker ps | grep sqlserver | awk '{print $1}')
+        echo "copy inventory SQL "
+        docker cp postgres/contrib/synchdb/inventory.sql $id:/
+        echo "SQL Server logs:"
+        docker logs $id
+        echo "Attempting to connect to SQL Server without SSL verification:"
+        docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -C -Q "SELECT @@VERSION"
+        echo "Executing inventory.sql:"
+        docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -C -i /inventory.sql
+        echo "Checking orders table:"
+        docker exec -i $id /opt/mssql-tools18/bin/sqlcmd -U sa -P 'Password!' -C -d testDB -Q "SELECT COUNT(*) from orders"        
     - name: Test synchdb MySQL
       run: |
         psql -d postgres -c "CREATE EXTENSION synchdb CASCADE;" || { echo "synchdb installation failed"; exit 1; }
@@ -134,7 +160,6 @@ jobs:
         SELECT synchdb_start_engine_bgw('mysqlconn');
         SELECT synchdb_start_engine_bgw('sqlserverconn');
         EOF
-
     - name: View connector states and validate
       run: |
         max_attempts=10
